import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const noto = Noto_Sans_JP({
  weight: '400',
  preload: false
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={noto.className}>
        <div className="flex flex-col min-h-screen">
          <header className="flex flex-row items-center px-24 py-4 bg-slate-200">
            <Image
              src="/logo.svg"
              alt="Logo"
              width={60}
              height={60}
            />
            <nav className="flex flex-row ml-auto">
              <ul className="flex flex-row gap-4">
                <li>
                  <a href="/">Home</a>
                </li>
                <li>
                  <a href="/about">About</a>
                </li>
              </ul>
            </nav>
          </header>
          <main className="flex-1">
            {children}
          </main>
          <footer className="bg-slate-500">
            <span className="text-sm text-slate-100">2024 muranuun</span>
          </footer>
        </div>
      </body>
    </html>
  );
}
